/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Formatter;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jordan
 */
public class Ajustes extends javax.swing.JDialog {
    public boolean existe;
    private Manejador manejador;
    private DefaultListModel modeloLista;
    private Formatter salida;
    private Scanner entrada;
    
    public Ajustes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setVisible(false);
        modeloLista = new DefaultListModel();
        manejador = new Manejador();
        initComponents();
        setLocationRelativeTo(parent);
        setManejadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entradaTexto = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajustes");
        setMinimumSize(new java.awt.Dimension(290, 350));
        setPreferredSize(new java.awt.Dimension(290, 350));
        setResizable(false);

        entradaTexto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        entradaTexto.setFocusCycleRoot(true);
        entradaTexto.setMaximumSize(new java.awt.Dimension(59, 20));
        entradaTexto.setMinimumSize(new java.awt.Dimension(59, 20));

        botonGuardar.setText("Guardar archivo");

        jList.setBackground(new java.awt.Color(204, 204, 204));
        jList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ingrese las palabras para el juego.");

        botonBorrar.setText("Borrar archivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(entradaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(entradaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(botonGuardar)
                .addGap(7, 7, 7)
                .addComponent(botonBorrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setManejadores(){
        entradaTexto.addActionListener(manejador);        
        botonGuardar.addActionListener(manejador);
        botonBorrar.addActionListener(manejador);
    
    }
    
    public void ajustar(){
        if (existeArchivo())
            leerArchivo();
        
        entradaTexto.requestFocus();
        setVisible(true);
    }
    
    private void crearArchivo(){
        if (modeloLista.getSize() < 5) {
            JOptionPane.showMessageDialog(null, "Debe ingresar 5 palabras como mínimo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            salida = new Formatter("Palabras.txt");
            
            for (int i = 0; i < modeloLista.getSize(); i++)
                salida.format("%s ", modeloLista.get(i));
            
            salida.close();
            setVisible(false);
        }
        
        catch (FileNotFoundException error){
            System.err.println(error.getMessage());
        }
        
    }
    
    private void leerArchivo(){
        try {
            entrada = new Scanner(new File("Palabras.txt"));
            modeloLista.clear();
            
            while (entrada.hasNext())
                modeloLista.addElement(entrada.next());

            jList.setModel(modeloLista);
            entrada.close();
        }
        
        catch(FileNotFoundException error){
            System.err.println(error.getMessage());
            
        }
        
    }

    private void borrarArchivo(){
        if (existeArchivo()){
            new File("Palabras.txt").delete();
            modeloLista.clear();
            jList.setModel(modeloLista);
        }
        
        modeloLista.clear();
        jList.setModel(modeloLista);
    }
    
    public boolean existeArchivo(){
        return new File("Palabras.txt").exists();
    }
    
    private boolean esValida(){
        return (!entradaTexto.getText().matches("^.*\\d.*$") && !entradaTexto.getText().contains(" ") && !modeloLista.contains(entradaTexto.getText()));        
    }

    private class Manejador implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource().equals(entradaTexto)) {
                if (!esValida()){
                    JOptionPane.showMessageDialog(null, "La palabra no es válida o ya se encontraba en el archivo.", "Error", JOptionPane.ERROR_MESSAGE);
                    entradaTexto.setText("");
                    return;
                }
                modeloLista.addElement(entradaTexto.getText());
                jList.setModel(modeloLista);
                entradaTexto.setText("");

            }
            else
                if (e.getSource().equals(botonGuardar))
                    crearArchivo();
                else
                    if (e.getSource().equals(botonBorrar))
                        borrarArchivo();
                
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField entradaTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}